---
title: "Visualisation and analysis of probability distributions of variables defined on  spatio-temporal granularities"
type: "contributed"
author: "<br> Sayani Gupta <br> <i class='fab fa-twitter' style='color:#6CADDE'></i> <i class='fab fa-github'></i> @Sayani07"
date: <font size="5"> Department of Econometrics and Business Statistics <br> February 28, 2019
output:
  xaringan::moon_reader:
    css: ["default", "data_viz_theme.css"]
    self_contained: false
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
library(knitr)
options(htmltools.dir.version = FALSE, tibble.width = 55, tibble.print_min = 4)
opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE, comment = "#>",
  fig.path = 'figure/', cache.path = 'cache/', fig.align = 'center', 
  fig.width = 12, fig.show = 'hold', fig.height = 8.5, # 16:9
  cache = TRUE, external = TRUE, dev = 'svglite'
)
read_chunk('R/theme.R')
read_chunk('R/main.R')
```

# <span style="color:DarkBlue"> Agenda

- Motivation
- Research aim
- What is EDA? How it can help?
- Research objectives
  - Visualizing probability distributions on deconstructed time
  - Spatio-temporal granularities and probability distribution plots
  - Clustering algorithms for grouping probability distributions on spatio-temporal granularities
- Timeline
- Acknowledgements

---

# <span style="color:DarkBlue"> Motivation

## Electricity smart meter technology 

Smart meters record electricity usage (per kWh) every 30 minutes and send this information to the electricity retailer for billing

.pull-left[
**Consumers** can save considerable amount on their electricity bill by 
<br>
- Switching on their hot water heater or do laundry when energy is cheaper, or when their solar system is generating surplus energy 
- Switching off appliances during peak demands
- Check usage and compare with similar homes 
]
.pull-right[

**Retailers** can reduce costs and increase efficiency
- Lowering metering and connection fees 
- Drawing insights into when customer is home, or sleeping, or even what appliances they are using based on usage figures
- Rewarding customers for mindful usage
]
